import { useState } from "react";
import { ExternalLink, Github, ArrowUpRight, ShieldCheck, Smartphone, CreditCard, Home, Sparkles, Bell, FileText, Search, Building2, Users, BriefcaseBusiness, Scale, AlertTriangle, CheckCircle2, WalletCards, ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useTiltEffect } from "@/hooks/useTiltEffect";

const cozyVisual = "https://raw.githubusercontent.com/Stakmodsco/cozy3fts-luxury-shop/main/src/assets/hero-main.jpg";

const Window = ({ children, label }: { children: React.ReactNode; label: string }) => (
  <div className="relative w-[88%] h-[78%] overflow-hidden rounded-2xl border border-white/15 bg-[#071018]/95 shadow-2xl">
    <div className="h-8 border-b border-white/10 flex items-center gap-1.5 px-3"><i className="w-1.5 h-1.5 rounded-full bg-red-400/70"/><i className="w-1.5 h-1.5 rounded-full bg-amber-400/70"/><i className="w-1.5 h-1.5 rounded-full bg-emerald-400/70"/><span className="ml-2 text-[8px] uppercase tracking-[.2em] text-white/35">{label}</span></div>
    {children}
  </div>
);

const Metric = ({ label, value, accent = "text-primary" }: { label: string; value: string; accent?: string }) => <div className="rounded-lg border border-white/10 bg-white/[.04] p-2.5"><p className="text-[7px] uppercase tracking-widest text-white/35">{label}</p><p className={`mt-1 text-xs md:text-sm font-semibold ${accent}`}>{value}</p></div>;

const ProductVisual = ({ project }: { project: any }) => {
  switch (project.visual) {
    case "notme": return <div className="h-full w-full bg-gradient-to-br from-emerald-950 via-slate-950 to-cyan-950 flex items-center justify-center"><div className="relative h-[88%] aspect-[9/16] rounded-[1.8rem] border-[5px] border-slate-700 bg-[#f6f7f5] shadow-2xl overflow-hidden text-slate-900"><div className="h-5 bg-slate-900"/><div className="p-3"><div className="flex justify-between items-center"><div><p className="text-[7px] text-slate-400">Good morning</p><p className="text-[11px] font-bold">Your documents</p></div><div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center"><Smartphone className="w-3 h-3 text-emerald-700"/></div></div><div className="mt-3 rounded-xl bg-emerald-700 text-white p-3"><p className="text-[7px] opacity-70">NEXT REMINDER</p><p className="text-[10px] font-semibold mt-1">Insurance expires soon</p><div className="flex gap-1 mt-2"><span className="text-[6px] bg-white/15 px-1.5 py-1 rounded">Oct 24</span><span className="text-[6px] bg-white/15 px-1.5 py-1 rounded">9:00 AM</span></div></div><p className="text-[7px] font-semibold mt-3 mb-1.5">Recent documents</p>{["Passport","Car insurance","Lease agreement"].map((x,i)=><div key={x} className="flex items-center gap-2 py-1.5 border-b border-slate-200"><div className="p-1 rounded bg-slate-100"><FileText className="w-2.5 h-2.5"/></div><div className="flex-1"><p className="text-[7px] font-medium">{x}</p><div className="h-1 bg-slate-100 rounded mt-1"><div className={`h-full rounded bg-emerald-500 ${i===0?'w-1/4':i===1?'w-1/2':'w-3/4'}`}/></div></div></div>)}</div></div></div>;
    case "vibeguard": return <div className="h-full w-full bg-gradient-to-br from-indigo-950 via-slate-950 to-cyan-950 flex items-center justify-center"><Window label="Vibe Guard · Production Readiness"><div className="p-4"><div className="flex justify-between items-center mb-4"><div className="flex gap-2 items-center"><ShieldCheck className="w-5 h-5 text-cyan-400"/><div><p className="text-[10px] font-semibold text-white">Security posture</p><p className="text-[7px] text-white/40">AI-built application review</p></div></div><span className="text-[7px] text-emerald-400 border border-emerald-400/20 bg-emerald-400/10 rounded-full px-2 py-1">READY</span></div><div className="grid grid-cols-3 gap-2"><Metric label="Readiness" value="Verified" accent="text-emerald-400"/><Metric label="Hardening" value="92%"/><Metric label="Checks" value="24/24" accent="text-violet-400"/></div><div className="mt-3 space-y-2">{["Authentication & RLS","Input validation","Launch verification"].map((x,i)=><div key={x} className="flex items-center gap-2 rounded-lg bg-white/[.035] border border-white/[.07] px-2.5 py-2"><CheckCircle2 className="w-3 h-3 text-emerald-400"/><span className="text-[8px] text-white/65 flex-1">{x}</span><span className="text-[7px] text-white/30">{i===2?'Passed':'Secure'}</span></div>)}</div></div></Window></div>;
    case "payments": return <div className="h-full w-full bg-gradient-to-br from-violet-950 via-slate-950 to-cyan-950 flex items-center justify-center"><Window label="PayDouFlow · Payment Core"><div className="p-4"><div className="grid grid-cols-3 gap-2"><Metric label="Transactions" value="1,284"/><Metric label="Success" value="99.2%" accent="text-emerald-400"/><Metric label="Ledger" value="Balanced" accent="text-cyan-400"/></div><div className="mt-3 rounded-xl border border-white/10 overflow-hidden">{[["STK Push","KSh 4,500","Completed"],["Callback","KSh 12,000","Verified"],["Webhook","KSh 8,250","Signed"]].map(r=><div key={r[0]} className="grid grid-cols-3 px-3 py-2 border-b last:border-0 border-white/[.06] text-[7px]"><span className="text-white/65">{r[0]}</span><span className="text-white/45">{r[1]}</span><span className="text-emerald-400 text-right">{r[2]}</span></div>)}</div></div></Window></div>;
    case "ishi": return <div className="h-full w-full bg-gradient-to-br from-amber-950 via-slate-950 to-emerald-950 flex items-center justify-center"><Window label="Ishi · Verified Living"><div className="p-3"><div className="flex gap-2"><div className="flex-1 rounded-lg border border-white/10 bg-white/[.04] px-2 py-1.5 flex items-center gap-1"><Search className="w-2.5 h-2.5 text-white/40"/><span className="text-[7px] text-white/40">Nairobi · Kilimani</span></div><span className="text-[7px] bg-emerald-500 text-black rounded-lg px-2 py-1.5">Search</span></div><div className="grid grid-cols-3 gap-2 mt-3">{["Westlands","Kilimani","Kileleshwa"].map((x,i)=><div key={x} className="rounded-xl overflow-hidden border border-white/10 bg-white/[.04]"><div className={`h-14 ${i===0?'bg-gradient-to-br from-amber-700/60 to-slate-800':i===1?'bg-gradient-to-br from-emerald-800 to-slate-800':'bg-gradient-to-br from-orange-900 to-slate-800'} flex items-center justify-center`}><Building2 className="w-5 h-5 text-white/50"/></div><div className="p-2"><p className="text-[7px] font-medium text-white">{x}</p><p className="text-[6px] text-white/35 mt-1">Verified · 2 BR</p></div></div>)}</div></div></Window></div>;
    case "taskbridge": return <div className="h-full w-full bg-gradient-to-br from-blue-950 via-slate-950 to-indigo-950 flex items-center justify-center"><Window label="TaskBridge · Work Platform"><div className="p-4"><div className="flex justify-between"><div><p className="text-[10px] font-semibold text-white">Available tasks</p><p className="text-[7px] text-white/35">Matched to your skills</p></div><BriefcaseBusiness className="w-5 h-5 text-blue-400"/></div><div className="mt-3 space-y-2">{[["AI Response Evaluation","KSh 1,250"],["Data Annotation","KSh 800"],["Research & Writing","KSh 1,600"]].map((r,i)=><div key={r[0]} className="rounded-lg border border-white/10 bg-white/[.04] p-2 flex items-center gap-2"><div className="w-7 h-7 rounded-lg bg-blue-500/10 flex items-center justify-center"><Users className="w-3 h-3 text-blue-400"/></div><div className="flex-1"><p className="text-[7px] text-white/70">{r[0]}</p><p className="text-[6px] text-white/30">{i===0?'AI Training':'Remote · Verified'}</p></div><span className="text-[7px] text-emerald-400">{r[1]}</span></div>)}</div></div></Window></div>;
    case "balipa": return <div className="h-full w-full bg-gradient-to-br from-green-950 via-slate-950 to-teal-950 flex items-center justify-center"><Window label="Balipa · Paid. Balanced."><div className="p-3"><div className="flex justify-between mb-2"><div><p className="text-[9px] font-semibold text-white">Good morning.</p><p className="text-[6px] text-white/35">ABC Academy · Term 1</p></div><ReceiptText className="w-4 h-4 text-emerald-400"/></div><div className="grid grid-cols-4 gap-1.5"><Metric label="Expected" value="18.42M"/><Metric label="Paid" value="14.76M" accent="text-emerald-400"/><Metric label="Balance" value="3.66M" accent="text-amber-400"/><Metric label="Today" value="824.5K"/></div><div className="mt-2 rounded-lg border border-white/10 p-2"><div className="flex justify-between text-[6px] text-white/40"><span>Collection progress</span><span>80.1%</span></div><div className="h-1.5 bg-white/10 rounded mt-1.5 overflow-hidden"><div className="h-full w-4/5 bg-emerald-400 rounded"/></div></div></div></Window></div>;
    case "lexmind": return <div className="h-full w-full bg-gradient-to-br from-amber-950 via-slate-950 to-violet-950 flex items-center justify-center"><Window label="LexMind · Contract Workspace"><div className="p-4 flex gap-3 h-[calc(100%-2rem)]"><div className="w-1/3 rounded-lg border border-white/10 p-2"><Scale className="w-4 h-4 text-amber-400 mb-3"/>{["Documents","Generate","Refine","Billing"].map(x=><p key={x} className="text-[7px] text-white/45 py-1.5">{x}</p>)}</div><div className="flex-1 rounded-lg bg-white/[.04] border border-white/10 p-3"><p className="text-[8px] font-semibold text-white">Service Agreement</p>{[90,75,84,62,78].map((w,i)=><div key={i} className="h-1 bg-white/10 rounded mt-2" style={{width:`${w}%`}}/>)}<div className="mt-3 inline-flex text-[6px] text-violet-300 border border-violet-400/20 rounded px-2 py-1">AI refinement ready</div></div></div></Window></div>;
    case "soc": return <div className="h-full w-full bg-gradient-to-br from-red-950 via-slate-950 to-cyan-950 flex items-center justify-center"><Window label="SOC Genesis · Incident Triage"><div className="p-3"><div className="grid grid-cols-3 gap-2"><Metric label="Open alerts" value="18" accent="text-red-400"/><Metric label="Investigating" value="6" accent="text-amber-400"/><Metric label="Confidence" value="94%"/></div><div className="mt-2 space-y-1.5">{[["Suspicious login","Critical"],["Privilege escalation","High"],["Unusual API traffic","Medium"]].map(r=><div key={r[0]} className="flex items-center rounded-lg border border-white/10 px-2 py-2"><AlertTriangle className="w-3 h-3 text-red-400 mr-2"/><span className="text-[7px] text-white/65 flex-1">{r[0]}</span><span className="text-[6px] text-red-300">{r[1]}</span></div>)}</div></div></Window></div>;
    case "fino": return <div className="h-full w-full bg-gradient-to-br from-fuchsia-950 via-black to-amber-950 flex items-center justify-center"><div className="relative flex items-center justify-center w-full h-full"><div className="absolute w-36 h-36 rounded-full bg-amber-400/10 blur-2xl"/><div className="relative w-20 h-28 rounded-t-[2rem] rounded-b-xl border border-amber-200/30 bg-gradient-to-br from-amber-200/30 via-fuchsia-200/10 to-amber-700/30 shadow-[0_0_40px_rgba(251,191,36,.12)]"><div className="absolute -top-5 left-1/2 -translate-x-1/2 w-8 h-6 rounded-t bg-amber-200/40 border border-amber-100/20"/><div className="absolute inset-x-3 top-10 border-y border-amber-100/20 py-2 text-center"><p className="text-[7px] tracking-[.25em] text-amber-100">FINO</p><p className="text-[6px] tracking-[.18em] text-amber-200/60">FIORE</p></div></div>{["OUD","ROSE","AMBER"].map((x,i)=><span key={x} className="absolute text-[6px] tracking-[.2em] text-amber-100/45" style={{transform:`translate(${(i-1)*85}px, ${i%2?70:-65}px)`}}>{x}</span>)}</div></div>;
    default: return <div className={`h-full w-full bg-gradient-to-br ${project.gradient || "from-primary/25 via-background to-secondary/20"} flex items-center justify-center`}><Window label={project.stage}><div className="p-5 flex items-center justify-center h-[calc(100%-2rem)]"><Sparkles className="w-10 h-10 text-primary/60"/></div></Window></div>;
  }
};

const ProjectCard = ({ project, index }: { project: any; index: number }) => {
  const tiltRef = useTiltEffect<HTMLDivElement>();
  return <article ref={tiltRef} className={`glass-card rounded-[1.6rem] overflow-hidden group border border-white/10 hover:border-primary/30 hover:shadow-[0_0_45px_rgba(0,188,212,0.18)] transition-all duration-500 animate-flow-in ${project.featured ? "md:col-span-2" : ""}`} style={{ animationDelay:`${index*.08}s`, transformStyle:"preserve-3d", willChange:"transform" }}>
    <div className={`relative overflow-hidden ${project.featured ? "h-72 md:h-[24rem]" : "h-56"}`}>{project.image ? <img src={project.image} alt={`${project.title} project interface`} className="w-full h-full object-cover group-hover:scale-[1.035] transition-transform duration-700" loading="lazy"/> : <ProductVisual project={project}/>}<div className="absolute inset-0 bg-gradient-to-t from-background via-background/5 to-transparent pointer-events-none"/><div className="absolute top-4 left-4 rounded-full border border-white/15 bg-background/75 backdrop-blur-xl px-3 py-1.5 text-[11px] uppercase tracking-[.14em] font-semibold">{project.stage}</div>{project.featured&&<div className="absolute top-4 right-4 rounded-full bg-primary text-primary-foreground px-3 py-1.5 text-[11px] uppercase tracking-[.14em] font-bold">Featured</div>}</div>
    <div className="p-6 md:p-7"><div className="flex items-start justify-between gap-4 mb-3"><h3 className="text-xl md:text-2xl font-bold">{project.title}</h3><ArrowUpRight className="h-5 w-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-all"/></div><p className="text-sm text-muted-foreground mb-5 leading-relaxed">{project.description}</p><div className="flex flex-wrap gap-2 mb-5">{project.tags.map((tag:string)=><span key={tag} className="px-2.5 py-1 text-[11px] rounded-full bg-primary/10 text-primary border border-primary/15">{tag}</span>)}</div><div className="flex flex-wrap gap-4 border-t border-white/10 pt-4">{project.demo&&<a href={project.demo} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm font-medium hover:text-primary transition-colors"><ExternalLink className="h-4 w-4"/> Live experience</a>}{project.repo&&<a href={project.repo} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"><Github className="h-4 w-4"/> Repository</a>}</div></div>
  </article>;
};

export const Projects = () => {
  const [activeFilter,setActiveFilter]=useState("all");
  const projects=[
    {title:"NotMe",category:"mobile",stage:"Mobile · Cloud",featured:true,visual:"notme",description:"Production-hardened iOS and Android document-expiry product with reminders, AI-assisted document workflows, secure authentication, subscriptions, cloud migration, background processing, and release engineering.",tags:["React Native","Expo","TypeScript","FastAPI","Supabase","RevenueCat","AWS"]},
    {title:"Vibe Guard",category:"security",stage:"Security · AI",featured:true,visual:"vibeguard",description:"Developer security and production-readiness SaaS for AI-built and vibe-coded applications, covering cleanup, secure implementation patterns, verification, launch readiness, premium access, and stack-specific security guidance.",tags:["React","TypeScript","Supabase","RLS","Edge Functions","Security","SaaS"]},
    {title:"Cozy3fts Luxury Shop",category:"commerce",stage:"Commerce · UI/UX",featured:true,image:cozyVisual,description:"A complete luxury fashion storefront with editorial visual direction, responsive shopping, product detail flows, cart and wishlist state, checkout, order tracking, thrift and new-arrival collections, admin tooling, and image-protection features.",tags:["React","TypeScript","E-Commerce","Cart","Wishlist","Checkout","Responsive UX"],demo:"https://cozy3fts-luxury-shop.vercel.app",repo:"https://github.com/Stakmodsco/cozy3fts-luxury-shop"},
    {title:"PayDouFlow",category:"fintech",stage:"Fintech · Infrastructure",visual:"payments",description:"M-Pesa/Daraja payment core engineered around encrypted credentials, tenant isolation, idempotent callbacks, immutable ledgers, atomic finalization, signed webhooks, replay protection, diagnostics, and transaction repair tooling.",tags:["M-Pesa","Daraja","Supabase","RLS","AES-256-GCM","Webhooks","Ledger"]},
    {title:"Ishi Property Hub",category:"platform",stage:"Property · Mobile",visual:"ishi",description:"Verification-led Kenyan property platform for vetted short stays, rentals, vacancy alerts and house-hunter discovery, with controlled publishing, owner approvals, partner workflows and mobile-first delivery.",tags:["React","TypeScript","Supabase","Capacitor","Property Tech","Mobile UX"]},
    {title:"TaskBridge",category:"platform",stage:"Work Platform",visual:"taskbridge",description:"Kenyan digital-work platform connecting talent with paid AI training, annotation, transcription, moderation, writing, research and evaluation tasks, with eligibility, security and payout-oriented product flows.",tags:["React","TypeScript","TanStack Router","Supabase","Auth","M-Pesa UX"],repo:"https://github.com/Stakmodsco/taskbridge-connect"},
    {title:"Balipa",category:"fintech",stage:"Billing · Kenya",visual:"balipa",description:"Billing and reconciliation infrastructure for school fees and rentals: account records, fee structures, payment allocation, paid/outstanding/credit balances, receipts, statements, reporting and notification-ready workflows.",tags:["Next.js","TypeScript","FastAPI","PostgreSQL","Redis","Billing","M-Pesa"]},
    {title:"LexMind AI Contracts",category:"ai",stage:"Legal AI",visual:"lexmind",description:"AI-assisted contract product with generation and refinement workflows, document management, billing, authentication, account settings and a complete SaaS dashboard experience.",tags:["React","TypeScript","AI","SaaS","Documents","Billing","Framer Motion"]},
    {title:"SOC Genesis AI",category:"security",stage:"Cybersecurity · AI",visual:"soc",description:"Security-operations interface for alert ingestion, incident triage, incident analysis, confidence scoring, metrics and operational settings, exploring AI-assisted SOC response workflows.",tags:["React","TypeScript","Cybersecurity","Incident Triage","SOC","Analytics"]},
    {title:"Medical Billing AI",category:"ai",stage:"Healthcare · AI",image:"https://res.cloudinary.com/dud0zwl1t/image/upload/v1758122328/revenue-glide-ai_ljl1bd.png",description:"Healthcare revenue and billing product with dashboard experiences, revenue and expense views, ROI tooling, security and pricing surfaces, and enterprise-facing product UX.",tags:["React","TypeScript","Supabase","Healthcare","Revenue Analytics"],demo:"https://medical-billing-ai-theta.vercel.app/"},
    {title:"Theos Educational Platform",category:"platform",stage:"EdTech",image:"https://res.cloudinary.com/dud0zwl1t/image/upload/v1758119072/Student_Dashboard_-_theos_Educational_Platform_1_msrqdd.png",description:"Cross-platform theological learning experience with structured educational content and dashboard-led learning UX across web and application delivery.",tags:["Flutter","React","Python","FastAPI","EdTech"],demo:"https://stakmodsco.github.io/theos_educational_platform/",repo:"https://github.com/Stakmodsco/theos_educational_platform"},
    {title:"AI Personal COO",category:"ai",stage:"AI · Operations",image:"https://res.cloudinary.com/dud0zwl1t/image/upload/v1761232577/AI_Personal_COO_-_Your_Intelligent_Executive_Assistant_qlaq2e.png",description:"Executive operations assistant focused on workflow automation, operational visibility, decision support and AI-assisted business execution.",tags:["React","TypeScript","AI Automation","Operations","Product UX"],demo:"https://ai-personal-coo.vercel.app/",repo:"https://github.com/Stakmodsco/AI-Personal-COO"},
    {title:"Fino Fiore",category:"commerce",stage:"Luxury · Commerce",visual:"fino",description:"Luxury fragrance commerce direction combining catalog architecture, Kenya-specific pricing, premium imagery and cinematic perfume-note storytelling through motion-led product presentation.",tags:["React","TypeScript","Commerce","UI/UX","Motion","Storytelling"]}
  ];
  const filters=[{id:"all",label:"All Selected Work"},{id:"mobile",label:"Mobile"},{id:"ai",label:"AI"},{id:"fintech",label:"Fintech"},{id:"security",label:"Security"},{id:"platform",label:"Platforms"},{id:"commerce",label:"Commerce & UI/UX"}];
  const filteredProjects=activeFilter==="all"?projects:projects.filter(p=>p.category===activeFilter);
  return <section id="projects" className="py-20 md:py-32 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-background via-secondary/5 to-background"/><div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10"><div className="max-w-7xl mx-auto"><div className="mb-12 md:mb-16 animate-flow-in"><p className="text-xs uppercase tracking-[.28em] text-primary font-semibold mb-4">Selected portfolio</p><div className="grid lg:grid-cols-2 gap-6 items-end"><h2 className="text-4xl md:text-6xl font-bold leading-[1.05]">Products should be <span className="text-shimmer">seen, not just listed.</span></h2><p className="text-lg text-muted-foreground lg:pb-1">A visual collection of production engineering, mobile products, AI systems, fintech infrastructure, security tooling and premium interfaces — with project-specific product previews instead of generic placeholders.</p></div></div><div className="flex flex-wrap gap-2 mb-10">{filters.map(f=><Button key={f.id} variant={activeFilter===f.id?"default":"outline"} size="sm" onClick={()=>setActiveFilter(f.id)}>{f.label}</Button>)}</div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-7">{filteredProjects.map((p,i)=><ProjectCard key={p.title} project={p} index={i}/>)}</div><div className="mt-14 glass-card rounded-[1.6rem] p-7 md:p-9 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 border border-white/10"><div><p className="text-xs uppercase tracking-[.2em] text-primary mb-2">Beyond the highlights</p><h3 className="text-2xl font-bold mb-2">The portfolio is curated. The repository history is broader.</h3><p className="text-sm text-muted-foreground max-w-3xl">Additional cybersecurity products, commerce builds, SaaS experiments, finance products, mobility concepts and earlier interface explorations remain available on GitHub without crowding the main case-study wall.</p></div><a href="https://github.com/Stakmodsco?tab=repositories" target="_blank" rel="noopener noreferrer"><Button variant="outline" className="whitespace-nowrap"><Github className="h-4 w-4 mr-2"/> Explore GitHub</Button></a></div></div></div></section>;
};
