name: Cleanup Lockfile

on:
  push:
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  regenerate-lockfile:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing commits

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove old lockfile and node_modules
        run: rm -rf package-lock.json node_modules

      - name: Reinstall dependencies
        run: npm install

      - name: Commit and push updated lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "CI: regenerate lockfile after package.json update" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
